# Generated by Django 4.2.2 on 2023-07-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0002_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='jornada',
            field=models.CharField(choices=[('M', 'MATUTINO'), ('V', 'VESPERTINO'), ('N', 'NOCTURNO')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='docente',
            name='sexo',
            field=models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMENINO')], max_length=1, null=True),
        ),
    ]
